# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [11]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [12]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set

path = 'Temp/'

In [13]:
#Your code starts here
entries = os.listdir(path)

for entry in entries:
    if entry.endswith('.txt'):
        file_count+=1
        files_dict.update({file_count:path+entry})
print(files_dict)

#Your code ends here       

{1: 'Temp/temp1.txt', 2: 'Temp/temp2.txt', 3: 'Temp/temp3.txt'}


Displaying the count of files.

In [15]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [16]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {1: 'Temp/temp1.txt', 2: 'Temp/temp2.txt', 3: 'Temp/temp3.txt'}


# Step 3 Extract Unique Vocabulary

In [17]:
# write code to print all the unique words in every file and store them in a set
# opening the text file
for file_name in files_dict.values():
    with open(file_name,'r') as file:
        # reading each line    
        for line in file:
            # reading each word        
            for word in line.split():
                # displaying the words           
                unique_word_set.add(word)

print(unique_word_set)

{'first', 'file.', 'another', 'This', 'temp3', 'unique', 'is'}


In [18]:
#Your code starts here    
print(unique_word_set)
print(file_count)
#Your code ends here

{'first', 'file.', 'another', 'This', 'temp3', 'unique', 'is'}
3


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [19]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words

term_doc = np.zeros((len(files_dict),len(unique_word_set)), dtype = 'int32')
print("TERM DOC INITIALLY")
print(term_doc)

TERM DOC INITIALLY
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [20]:
#Your code starts here 
counter = 0
words_dict = {}
for word in unique_word_set:
    words_dict[word] = counter
    counter += 1
print(words_dict)

counter = 0
files_new_dict = {}
for file_name in files_dict.values():
    files_new_dict[file_name] = counter
    counter += 1
print(files_new_dict)
#Your code ends here

{'first': 0, 'file.': 1, 'another': 2, 'This': 3, 'temp3': 4, 'unique': 5, 'is': 6}
{'Temp/temp1.txt': 0, 'Temp/temp2.txt': 1, 'Temp/temp3.txt': 2}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [21]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [23]:
#Your code starts here 

for file_name in files_new_dict:
    for word in words_dict:
        with open(file_name,'r') as file:
            allWords = file.read().split()
            occurences = allWords.count(word)
            if(occurences > 0):
                term_doc[files_new_dict[file_name]][words_dict[word]] = 1
print("TERM DOC After")
print(term_doc)
#Your code ends here

TERM DOC After
[[1 1 0 1 0 0 1]
 [0 1 1 1 0 1 1]
 [0 1 0 1 1 0 1]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [24]:
# For user query make a column vector of length of all the unique words present in a set

In [25]:
#Your code starts here    

col_vector = np.zeros((len(words_dict),1),dtype = 'int32')
print(col_vector)

#Your code ends here

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


### Expected Output

<img src="7.png"/>

In [26]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary




Write something for searching  is this is another file temp2


In [27]:
#Your code starts here    
query_words = query.split()
for qword in query_words:
    if qword in words_dict:
        col_vector[words_dict[qword]] += 1
#Your code ends here

### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [28]:
#Your code starts here  
print("Resultant Vector")
print(col_vector)

mx = max(col_vector)[0]
print("Max in Resultant: ")
print(mx)

def getIndexOfMax(col_vector,mx):
    counter = 0
    for val in col_vector:
        if(val == mx):
            return counter
        else:
            counter += 1

idx = getIndexOfMax(col_vector,mx)

print("Index of max in resultant is: ")
print(idx)

            #Your code ends here

Resultant Vector
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [2]]
Max in Resultant: 
2
Index of max in resultant is: 
6


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [29]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [30]:
#Your code starts here
def get_file_name(files_new_dict,term_doc,idx):
    for key in files_new_dict:
        if(term_doc[files_new_dict[key]][idx] == 1):
            return key
        
fname = get_file_name(files_new_dict,term_doc,idx)
print(fname+":\n")
with open(fname,'r') as file:
    dataString = file.read()
    print("\""+dataString+"\"")
    

#Your code ends here

Temp/temp1.txt:

"This is first file."


Congratulations Now you are able to build your own small IRS.